CREATE TABLE dbo.Branches (
    BranchId    INT IDENTITY(1,1) PRIMARY KEY,
    BranchName  NVARCHAR(100) NOT NULL UNIQUE,
    Address     NVARCHAR(250) NOT NULL,
    CreatedDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
